apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    appname: employee-pod
  type: NodePort
  ports:
    - name: employee-port
      nodePort: 30001
      port: 8000
      targetPort: 8000