apiVersion: v1
kind: Service
metadata:
  name: gradle-service
spec:
  selector:
    appname: gradle-pod
  type: NodePort
  ports:
    - name: gradle-port
      nodePort: 30002
      port: 8000
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradle-app
  labels:
    name: gradle-app
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: gradle-pod
  template:
    metadata:
      name: gradle-pod
      labels:
        appname: gradle-pod
    spec:
      containers:
        - name: gradle-container
          image: vinothg2309/sample-gradle
          ports:
            - containerPort: 8080
              protocol: TCP
