---
# Source: employee-service-helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: employee-service-helm-0.1.0
    app.kubernetes.io/name: employee-service-helm
    app.kubernetes.io/instance: emp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  name: "employee-service"
spec:
  selector:
    app.kubernetes.io/name: employee-service-helm
    app.kubernetes.io/instance: emp
  type: NodePort
  ports:
    - name: employee-port
      nodePort: 30001
      port: 8080
      targetPort: 8000
---
# Source: employee-service-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    helm.sh/chart: employee-service-helm-0.1.0
    app.kubernetes.io/name: employee-service-helm
    app.kubernetes.io/instance: emp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: employee-service-helm
      app.kubernetes.io/instance: emp
  template:
    metadata:
      name: employee-pod
      labels:
        app.kubernetes.io/name: employee-service-helm
        app.kubernetes.io/instance: emp
    spec:
      containers:
        - name: employee-container
          image: vinothg2309/employee-service
          env:
          - name: MONGO_DB_NAME
            value: test
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_HOST
            value: mongodb
          - name: MONGODB_URI
            value: mongodb://mongodb:27017/test
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "2000m"
