apiVersion: batch/v1
kind: Job
metadata:
    name: pi
spec:
    ttlSecondsAfterFinished: 100 # TTL(Time To Live) controller cleans up the Job, it will delete the Job cascadingly, i.e. delete its dependent objects, such as Pods, together with the Job
    backoffLimit: 4 # to specify the number of retries before considering a Job as failed. The back-off limit is set by default to 6. 
    template:
        spec:
            containers:
                - name: pi
                  image: perl
                  command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
            restartPolicy: Never
    
    
    
    