apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
    accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 10Gi
  hostPath:
    path: "/mnt/data"
