apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6}}
  template:
    metadata:
      name: employee-pod
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: employee-container
          image: {{ .Values.image.repository }}
          env:
            {{- toYaml .Values.env | nindent 10}}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- include "helm-chart.resources" . | nindent 10}}