apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  name: {{ .Values.service.name | quote }}
spec:
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4}}
  type: {{ .Values.service.type }}
  ports:
    - name: employee-port
      nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}