apiVersion: v1
kind: Service
metadata:
  labels:
    name: angular-app-public
    role: blue
    env: prod
  name: angular-app-public
spec:
  ports:
    - protocol: "TCP"
      port: 4200
      targetPort: 4200
  type: LoadBalancer
  selector:
    app: angular-app-$TARGET_ROLE
    role: $TARGET_ROLE