apiVersion: v1
kind: Service
metadata:
  labels:
    name: angular-app-$TARGET_ROLE
    role: blue
    env: test
  name: angular-app-$TARGET_ROLE
spec:
  ports:
    - protocol: "TCP"
      port: 4000
      targetPort: 4200
  type: LoadBalancer
  selector:
    app: angular-app
    role: $TARGET_ROLE