apiVersion: v1
kind: Service
metadata:
  labels:
    name: angular-app
  name: angular-app
spec:
  ports:
    - protocol: "TCP"
      port: 4200
      targetPort: 4200
      nodePort: 30100
  type: NodePort
  selector:
    run: angular-app